name: Haos ARP Syncing
version: "1.0.8"
slug: haos-arp-syncing
description: |
  haos-arp-syncing is a lightweight service that synchronizes ARP tables across multiple network interfaces to ensure consistent device discovery and connectivity.
  It is particularly useful in environments with multiple subnets or VLANs, where devices may not be visible across different network segments.
  By keeping ARP tables in sync, haos-arp-syncing helps maintain seamless communication between devices, improving network reliability and performance.
  This add-on is ideal for home labs, small office networks, and any setup that requires robust device discovery across diverse network configurations.
  
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
ingress: false

# Quan trọng: bật host network để mDNS hoạt động
host_network: true 

map:
  - config:rw
  - share:rw
  - media:rw
  - ssl:ro

schema:
  ip: str?
  username: str?
  password: str?
options:
  ip: ''
  username: ''
  password: ''